### ISSUE TITLE
Skip invoking `main()` if script is itself being sourced

### ISSUE THREAD

**Issue by ClashTheBunny** [ralish/bash-script-template#11]
When testing high cost steps for a script, or with many prerequisites, I've found it nice to have all functions souceable.  This works on bash and zsh, but is simplify-able for just bash:
https://github.com/ClashTheBunny/Debian64Pi/blob/08dce517a538dd877ea106af882c7f00c0b90117/build.sh#L266
This way, I can create, mount, run debootstrap, and then experiment with the next function of the script.  Without this, it unmounts and I need to test it from the beginning again.  This makes the later stage functions easier to iterate on.

This is like the `if main` construct in Python.

**Comment by ralish** [comment]
That's pretty neat! I can definitely see the utility of this. Will see about getting something added when I get the chance (might not be until the Xmas break).

**Comment by ClashTheBunny** [comment]
I think it came from here: https://stackoverflow.com/a/28776166

**Comment by ralish** [comment]
Initial implementation is on a separate branch. See this commit: https://github.com/ralish/bash-script-template/commit/668ee7c0841660fa5b15a347832238669e31e18f

It's a little trickier in our case as along with skipping execution of `main()` it seems like a good idea to avoid setting some shell behaviours on the assumption we're being sourced into an interactive shell, in which case those behaviours may not be desired.

Any thoughts?

**Comment by ralish** [comment]
Merged, but if you have any thoughts feel free to add a comment.
