### ISSUE TITLE
Purpose of `[ printf '%b' "$ta_none" ]` when initialising colours

### ISSUE THREAD

**Issue by onelittlehope** [ralish/bash-script-template#12]
May I know why the following line is executed after assigning the output of a tput command to a variable?

```
printf '%b' "$ta_none"
```

e.g. https://github.com/ralish/bash-script-template/blob/main/template.sh#L144-L189

Afaict the tput command outputs to stdout which is captured by the `$(...)` and saved into the variable. So at no point would it affect the terminal's current state.

I may be missing something and hence the query.

**Comment by ralish** [comment]
During normal script execution you're right that this is redundant, but there's an edge-case where it's useful: running the script with `xtrace`. When the script commands are being output to the terminal each `tput` will also affect the terminal state, so we clear all text attributes after each invocation so the terminal output doesn't become completely mangled.

**Comment by ralish** [comment]
I've added a comment noting the above as agree it's less than obvious: https://github.com/ralish/bash-script-template/commit/94509804b494e84793f266dec9428262ec172fa6

Closing this issue but feel free to re-open if there's anything else.
