### ISSUE TITLE
Lock functionality for single instance

### ISSUE THREAD

**Issue by jankatins** [ralish/bash-script-template#2]
Seeing this repo/script, I expected some kind of locking functionality build into the scripts.

**Comment by ralish** [comment]
Can you provide some more details on what you have in mind? Enforcing a single instance of the script, or were you thinking of a more generic function?

**Comment by jankatins** [comment]
Single instance script would already be great. I wanted to use it to both ensure single instance and use the lockfiles access time to trigger reruns of the functionality (rerun sync when a file changed during the already running sync).

Examples might be here: http://wiki.bash-hackers.org/howto/mutex

**Comment by ralish** [comment]
Interesting, will see about adding something appropriate soon.

**Comment by ralish** [comment]
I've added basic locking support to ensure only a single instance of the script is running, scoped at either the system or user level. Support is provided by the new `lock_init()` function which is called by `main()` but commented out by default. The support is basic, but as far as I can tell, anything more sophisticated can't be done in a platform agnostic way, and for now, I'm keen to keep the code free of any platform specific code.

See commit 1d8c17abff459715281cdda5842aab2d34cd6fe7 for additional details.
