### ISSUE TITLE
Additional command line parameters

### ISSUE THREAD

**Issue by cjhelmkamp** [ralish/bash-script-template#3]
In your template it might help to have an example or two of additional command line parameters. In the following i have added Hostname.

`# DESC: Parameter parser'`
`# ARGS: $@ (optional): Arguments provided to the script'`
`# OUTS: Variables indicating command-line parameters and options`
`function parse_params() {`
`    local param`
`    while [[ $# -gt 0 ]]; do`
`        param="$1"`
`        shift`
`        case $param in`
`            -H|--Hostname)`
`                Hostname=$1`
`                shift`
`                #shift`
`                ;;`
`            -h|--help)`
`                script_usage`
`                exit 0`
`                ;;`
`            -v|--verbose)`
`                verbose=true`
`                ;;`
`            -nc|--no-colour)`
`                no_colour=true`
`                ;;`
`            -cr|--cron)`
`                cron=true`
`                ;;`
`            *)`
`                script_exit "Invalid parameter was provided: $param" 2`
`                ;;`
`        esac`
`    done`
`}`
`

**Comment by ralish** [comment]
Good suggestion; I've added some additional guidance in the `README.md`.
