### ISSUE TITLE
Entrypoint to insert our script

### ISSUE THREAD

**Issue by pascalandy** [ralish/bash-script-template#4]
I would like to have your point of view on the way I should start adding scripts along your template. I decided to use the script/source setup.

I created a new function (splash.sh) and inserted it in the main function. Is this how it's supposed to work?

https://github.com/pascalandy/bash-script-template/blob/stable/splash.sh#L73

Thank you!
P

**Comment by ralish** [comment]
Yes, that's exactly right. If you're adding or removing script arguments you'll also want to update the `script_usage()` and `parse_params()` functions. Depending on your requirements, you can also remove some of the default parameters, such as colour and cron support, or enable locking support (see https://github.com/ralish/bash-script-template/commit/1d8c17abff459715281cdda5842aab2d34cd6fe7).

**Comment by pascalandy** [comment]
This is how [my template looks like](https://github.com/pascalandy/bash-script-template/blob/stable/script_template_duplicate-me.sh#L75) with a clear entrypoint. Thank you so much for your work!
