### ISSUE TITLE
Use `verbose_print()` for updating Sudo cached credentials notice

### ISSUE THREAD

**Issue by ghost** [ralish/bash-script-template#6]
https://github.com/ralish/bash-script-template/blob/ff628fcbe2e5fa6ddd4a96fdb013879a9ea75fe8/source.sh#L352

**Comment by ralish** [comment]
The rationale at the time was that it might not be obvious what credential you're being prompted for, but at least on the systems I just tested, the `sudo` password prompt is always prefixed with `[sudo]` so yes, that does make it a bit redundant.

**Comment by ralish** [comment]
Fixed in https://github.com/ralish/bash-script-template/commit/9ba36a646fe13779ddd2c009a1bdaae505e29649.
