### ISSUE TITLE
Rename `try_sudo` in `run_as_root()` to be less confusing

### ISSUE THREAD

**Issue by ghost** [ralish/bash-script-template#7]
This isn't an issue, but if try_sudo is set to true, I suspect that it should be tried with sudo and not vice versa.

https://github.com/ralish/bash-script-template/blob/9ba36a646fe13779ddd2c009a1bdaae505e29649/source.sh#L384-L388

**Comment by ralish** [comment]
The choice of variable name is admittedly very confusing as it's effectively controlling the opposite of what its name suggests. Not sure what I was thinking there to be honest. I've renamed it to `skip_sudo` in https://github.com/ralish/bash-script-template/commit/91997cc533afb54c09ee596102542c0d71514192.
